{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.primary.service.headless.annotations .Values.commonAnnotations }}
  annotations:
    {{- if or .Values.primary.service.headless.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.primary.service.headless.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: {{ coalesce .Values.primary.containerPorts.mysql .Values.primary.service.port }}
      protocol: TCP
      targetPort: mysql
    {{- if and .Values.metrics.enabled (gt (.Values.metrics.containerPorts.http | int) 0) }}
    - name: metrics
      port: {{ .Values.metrics.containerPorts.http }}
      protocol: TCP
      targetPort: metrics
    {{- end }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
